language: common-lisp

branches:
  only:
    - master
    - develop
    - /^ci-.*$/

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=allegro
    - LISP=abcl
    - LISP=clisp

matrix:
  allow_failures:
    - env: LISP=abcl
    - env: LISP=clisp

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - git clone --depth=1 git://github.com/privet-kitty/wild-package-inferred-system.git ~/lisp/wild-package-inferred-system
  - git clone --depth=1 git://github.com/edicl/cl-ppcre.git ~/lisp/cl-ppcre
  - git clone --depth=1 git://gitlab.common-lisp.net/alexandria/alexandria.git ~/lisp/alexandria

script:
  - ros -s fiveam -e '(ql:quickload :dufy/test)
                      (or (fiveam:run! (quote dufy/test:main-suite))
                          (uiop:quit 1))'

sudo: required
